/* # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. PLEASE DO NOT TOUCH IT. SIF SAID DON'T, SO JUST DON'T!*/

/**************************************************************************/
/*                      _____ _____ ______                                */ 
/*                     / ____|_   _|  ____|                               */
/*                    | (___   | | | |__                                  */
/*                     \___ \  | | |  __|                                 */
/*                    ____) |_| |_| |                                     */
/*                   |_____/|_____|_|                                     */
/**************************************************************************/
/*  AUTOMATED FILE                                                        */
/**************************************************************************/



// Default and named exports
export { default as time } from './time.ts';
export * from './time.ts';

// Named exports only
export * from './text.ts';